package com.heyperdesign.restaurants.common.domain.exceptions

enum class RequestErrorKeyValues {
    PASSWORD_VALIDATION,
    PHONE_VALIDATION,
    NAME_VALIDATION,
    EMAIL_VALIDATION,
    OTP_VALIDATION,
    CONFIRMATION_PASSWORD,
    ADDRESS_FIRST_PHONE_VALIDATION,
    ADDRESS_SECOND_PHONE_VALIDATION,
    ADDRESS_SECOND_PHONE_VALIDATION_MUST_BE_DIFFERENT,
    USER_MESSAGE_VALIDATION
}